export const preferidos = [
  {
    name: "El Elegante",
    price: 2000,
    description: `Chocolate`,
    img: "elegante.jpg",
    id: 1,
  },
  {
    name: "El Radiante",
    price: 2000,
    description: `Maracuyá`,
    img: "radiante.jpg",
    id: 2,
  },
  {
    name: "El Fresco",
    price: 2000,
    description: `Limón`,
    img: "fresco.jpg",
    id: 3,
  },
  {
    name: "El Exótico",
    price: 2000,
    description: `Mora`,
    img: "exotico.jpg",
    id: 4,
  },
];

export const macarons = [
  {
    name: "El Elegante",
    price: 2000,
    description: `Chocolate`,
    img: "elegante.jpg",
    id: 1,
  },
  {
    name: "El Radiante",
    price: 2000,
    description: `Maracuyá`,
    img: "radiante.jpg",
    id: 2,
  },
  {
    name: "El Fresco",
    price: 2000,
    description: `Limón`,
    img: "fresco.jpg",
    id: 3,
  },
  {
    name: "El Exótico",
    price: 2000,
    description: `Mora`,
    img: "exotico.jpg",
    id: 4,
  },
  {
    name: "El Apasionado",
    price: 2000,
    description: `Red Velvet`,
    img: "apasionado.jpg",
    id: 5,
  },
  {
    name: "El Fuerte",
    price: 2000,
    description: `Café`,
    img: "fuerte.jpg",
    id: 6,
  },

  {
    name: "El Sincero",
    price: 2000,
    description: `Chicle`,
    img: "sincero.jpg",
    id: 7,
  },
  {
    name: "El Tierno",
    price: 2000,
    description: `Fresa`,
    img: "tierno.jpg",
    id: 8,
  },
  {
    name: "El Clásico",
    price: 2000,
    description: `Mezcla tradicional`,
    img: "clasico.jpg",
    id: 9,
  },
  {
    name: "El Divertido",
    price: 2000,
    description: `Naranja`,
    img: "divertido.jpg",
    id: 10,
  },
  {
    name: "El Ligero",
    price: 2000,
    description: `Mezcla tradicional sin Azucar`,
    img: "ligero.jpg",
    id: 11,
  },
  {
    name: "El Inocente",
    price: 2000,
    description: `Vainilla`,
    img: "inocente.jpg",
    id: 12,
  },
];

export const SABORES = [
  "fresa",
  "tradicional",
  "chocolate",
  "vainilla",
  "maracuya",
  "limon",
  "mora",
  "red velvet",
  "chicle",
  "naranja",
  "tradicional sin azucar",
  "cafe",
];
export const COLORES = {
  tradicional: "#e3c0c9",
  fresa: "#fd237a",
  vainilla: "#cfcfcf",
  chocolate: "#343434",
  maracuya: "#fdde4d",
  limon: "#1adcb1",
  mora: "#a617e1",
  "red velvet": "#cb1717",
  chicle: "#0589b8",
  naranja: "#fb711b",
  "tradicional sin azucar": "#9abec7",
  cafe: "#7b4523",
};

export const PRESENTACIONES = [
  {
    name: "Caja de 6",
    price: 10000,
    description: `Ármala con tus preferidos`,
    img: "6mac.jpg",
    id: 106,
  },
  {
    name: "Caja de 10",
    price: 16000,
    description: `Ármala con tus preferidos`,
    img: "10mac.jpg",
    id: 2,
  },
  {
    name: "Caja de 18",
    price: 26000,
    description: `Ármala con tus preferidos`,
    img: "18mac.jpg",
    id: 3,
  },
];
